# docker-compose.yml
version: '3'

networks:
  server:
  data:

services:
  nginx:
    container_name: docker_env_nginx
    image: nginx:1.18 # stable version
    networks:
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/ssl/
      - ./:/var/www/html/laravel-docker
    restart: always

  php:
    container_name: docker_env_php
    build: ./php/
    expose:
      - 9000
    networks:
      - server
      - data
    volumes:
      - ./web/:/var/trp/
    restart: always

  redis:
    container_name: docker_env_redis
    image: redis:6.0 # stable version
    ports:
      - "6379:6379"
    networks:
      - data
    restart: always

  postgre:
    container_name: docker_env_postgre
    ports:
      - "5432:5432"
    image: "postgres:12.6"
    volumes:
      - /trp/database/dev/database_data:/var/lib/postgresql/data # persist data even if container shuts down
    networks:
      - data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always

  mysqldb:
    image: mysql:5.7
    platform: linux/amd64
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - data