version: '3'
services:
  mysqldb:
    image: mysql:5.7
    platform: linux/amd64
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-data:/var/lib/mysql
  nodejs-server:
    build:
      # dockerfile path
      context: ./server
      dockerfile: Dockerfile-server
    expose:
      - 3000
    ports:
      - "3000:3000"
    container_name: express
    # 開發環境使用 nodemon
    command: "nodemon app.js"
    depends_on: 
      - "mysqldb"
      - "vue-ui"
    volumes:
       - ./server:/usr/src/app
       - /usr/src/app/node_modules
  vue-ui:
    build:
      # dockerfile path
      context: ./frontEnd
      dockerfile: Dockerfile-vue
    working_dir: /app
    expose:
      - 8080
    ports:
      - 8080:8080
    container_name: vue-ui
    volumes:
       - ./frontEnd:/app/
volumes:
  mysql-data:
# docker run -v /Users/evan.gu/express-Vue:/usr/tmp -p 8080:80 -d node:12 /bin/sh -c "cd /usr/tmp; ls; cat package.json; npm install; npm start"